statusik: http://www.statusiki.pl/rss_descs.xml
rolfcopter: http://feeds2.feedburner.com/Roflcopter?format=xml
pron: http://pr0n.pl/pr0n.rss
dowcipy: http://dowcipy.autentyki.pl/rss.php5
dowcipy2: http://www.zbuki.pl/syndication.php?action=article
dowcipy3: http://dowcipy.zarty.biz/feed/