smbc: http://www.smbc-comics.com/rss.php
dilbert: "http://feeds.dilbert.com/DilbertDailyStrip?format=xml"
geekfun: http://feeds.feedburner.com/geekfunfeed
robots: http://conceptrobots.blogspot.com/feeds/posts/default
buni: http://bunicomic.com/feed/
boli: http://boli.blog.pl/index.rss
bobkomiks: http://www.bobkomiks.ownlog.com/index.rss
superpower: http://www.amazingsuperpowers.com/category/comics/feed/
adhd: http://paskudaruda.blogspot.com/feeds/posts/default?alt=rss
abastruse: http://abstrusegoose.com/feed
creatures: http://www.creaturespot.com/main/atom.xml
johnjohn: http://www.johnandjohn.nl/rss.php
kops: http://feeds.feedburner.com/Kops
newmans: http://bennewmanart.blogspot.com/feeds/posts/default
optiess: http://feeds.feedburner.com/Optipess
spiked_math: http://feeds.feedburner.com/SpikedMath
virtual_shakles: http://feeds.feedburner.com/VirtualShackles
xkdc: http://xkcd.com/rss.xml
pandy: http://pandyland.net/feed/